"""Project-wide constants and keyword maps."""

from __future__ import annotations

SUPPORTED_FAMILIES = {
    "bunt",
    "bases_loaded",
    "grand_slam",
    "triple",
    "challenge",
    "venue",
    "narrative",
    "subjective_highlight",
    # Extended families matching real Kalshi market titles
    "home_run",
    "strikeout",
    "no_hitter",
    "stolen_base",
    "hit",
    "generic_mlb",
}

# Broad hints that mark a market as baseball-related.
# Includes team names, common Kalshi title prefixes, and play terminology.
MLB_HINTS = (
    # Explicit tags Kalshi uses
    "mlb",
    "baseball",
    # Play terminology
    "inning",
    "ballpark",
    "pitcher",
    "batter",
    "home run",
    "homer",
    "grand slam",
    "bases loaded",
    "bunt",
    "bunted",
    "triple",
    "strikeout",
    "strike out",
    "no-hitter",
    "no hitter",
    "perfect game",
    "stolen base",
    "steal",
    "challenge",
    "mvp",
    "at bat",
    "walk off",
    "shutout",
    "double play",
    "extra innings",
    "hit by pitch",
    "rbi",
    "earned run",
    # Team names (covers "Yankees", "Red Sox", etc. in Kalshi titles)
    "yankees",
    "red sox",
    "dodgers",
    "cubs",
    "mets",
    "braves",
    "astros",
    "cardinals",
    "giants",
    "phillies",
    "nationals",
    "royals",
    "tigers",
    "mariners",
    "padres",
    "brewers",
    "reds",
    "rockies",
    "pirates",
    "marlins",
    "twins",
    "guardians",
    "white sox",
    "orioles",
    "rays",
    "rangers",
    "blue jays",
    "athletics",
    "angels",
    "diamondbacks",
)

VENUE_KEYWORDS = (
    "ball park",
    "ballpark",
    "field",
    "stadium",
    "park",
)

FAMILY_KEYWORDS = {
    "grand_slam": (
        "grand slam",
        "grand-slam",
    ),
    "bases_loaded": (
        "bases loaded",
        "bases are loaded",
        "load the bases",
    ),
    "bunt": (
        "bunt",
        "bunted",
        "sac bunt",
        "sacrifice bunt",
    ),
    "triple": (
        "triple",
    ),
    "challenge": (
        "challenge",
        "challenged",
        "replay review",
        "replay",
        "overturned",
    ),
    "narrative": (
        "mvp",
        "cy young",
        "rookie of the year",
        "all-star",
        "all star",
        "hall of fame",
    ),
    "subjective_highlight": (
        "what a catch",
        "great catch",
        "incredible catch",
        "web gem",
        "diving catch",
        "robbed",
    ),
    # Extended families
    "home_run": (
        "home run",
        "homer",
        "go yard",
        "homers",
        "hit a home run",
        "hit home run",
    ),
    "strikeout": (
        "strikeout",
        "strike out",
        "struck out",
        "strikeouts",
        "punch out",
    ),
    "no_hitter": (
        "no-hitter",
        "no hitter",
        "perfect game",
        "no hit",
    ),
    "stolen_base": (
        "stolen base",
        "steal",
        "steals",
        "stolen",
    ),
    "hit": (
        "get a hit",
        "record a hit",
        "multi-hit",
        "multi hit",
        "hits in the game",
    ),
}
